# fly.toml app configuration file generated for notanobilekhanh on 2023-08-25T13:14:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notanobilekhanh"
primary_region = "atl"
console_command = "/code/manage.py shell"

[build]
[env]
PORT = "8000"
DJANGO_SETTINGS_MODULE = "notanobile.settings"
BUCKET_NAME = "projects-6-5"
S3_BASE_URL = "https://s3.us-east-2.amazonaws.com/"

[deploy]
release_command = "poetry run python manage.py migrate"

[[statics]]
guest_path = "/app/static"
url_prefix = "/static/"


[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[scaling]
min = 1
max = 1

[[mounts]]
source = "main"
destination = "/app/media/"
