# Generated by Django 4.2.4 on 2023-08-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("number_of_persons", models.IntegerField()),
                ("Date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
