# Generated by Django 4.2.4 on 2023-08-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0006_aboutus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("bio", models.TextField()),
                ("image", models.ImageField(upload_to="chef/")),
            ],
            options={
                "verbose_name": "chef",
                "verbose_name_plural": "chef",
            },
        ),
    ]
