# Generated by Django 4.2.4 on 2023-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_chef"),
    ]

    operations = [
        migrations.CreateModel(
            name="Why_Choose_Us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "why choose us ",
                "verbose_name_plural": "why choose us ",
            },
        ),
    ]
