# Generated by Django 4.2.4 on 2023-08-21 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0008_why_choose_us"),
    ]

    operations = []
