# Generated by Django 4.2.4 on 2023-08-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0009_auto_20230821_1901"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "about us", "verbose_name_plural": "about us"},
        ),
    ]
