# Generated by Django 4.2.4 on 2023-08-22 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0011_meal_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="Date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
