# Generated by Django 4.2.4 on 2023-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_meal_wines'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(default='Pasta, eggs & Love ', max_length=500),
            preserve_default=False,
        ),
    ]
