# Generated by Django 4.2.4 on 2023-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0017_meal_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="Date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(verbose_name="Time"),
        ),
    ]
