# Generated by Django 4.2.4 on 2023-08-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0019_reservation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(
                default="admin/main_app/to/default/image.jpg", upload_to="about_us/"
            ),
        ),
    ]
