# Generated by Django 4.2.4 on 2023-08-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0021_reservation_first_name_reservation_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.CharField(),
        ),
    ]
