# Generated by Django 4.2.4 on 2023-08-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0022_remove_reservation_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.CharField(max_length=500),
        ),
    ]
