# Generated by Django 4.2.4 on 2023-08-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0023_alter_meal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chef",
            name="image",
            field=models.CharField(max_length=500),
        ),
    ]
